name: alemira
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - python=3.10
  - requests
  - locust
  - pyyaml
  - pandas
  - numpy
  - scikit-learn
  - pymongo
  - pytest-cov
  - selenium
  - webdriver-manager
